### ISSUE TITLE
Font issue

### ISSUE THREAD

**Issue by muwaqar** [chrisparnin/pm#1]
The reminder is displayed in different fonts on the following pages:
1. http://www.google.com (Arial)
2. http://www.awaztoday.co/News-Talk-Shows/42941/Off-The-Record-28th-August-2013.aspx (Times New Roman)

**Comment by chrisparnin** [comment]
Thanks for pointing this out.

In chrome, content scripts are executed in context of a webpage but in separate sandbox.  That means, any element is added to a page by the content script, it will pick up the same css rules as the host page.

There should be ways to make ignore or override the page's css rules for the reminders that I can look into.

**Comment by chrisparnin** [comment]
Addressed in 1.0.3
