### ISSUE TITLE
Favicon alerts

### ISSUE THREAD

**Issue by scottksmith95** [chrisparnin/pm#2]
I am pretty sure an update added favicon alerts. I like the idea, but I ended up disabling the extension because all my tabs has a red circle with a 0 in it. Would it be possible to only show those alerts for URLs that have alerts on them? This would make all the alerts with 0 not show up and provide a better use experience.

**Comment by cmoz** [comment]
Hey, I wondered too what that was, and for the URLs with notes on them it would be awesome, but ya it's too much for my browser as I'm a tab-a-holic :o  

## 

Christine
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)

**Comment by chrisparnin** [comment]
Sorry! I'll have a quick update to fix that today.

**Comment by chrisparnin** [comment]
Should be addressed in 1.0.4 of web store (may take a few mins to publish).
