### ISSUE TITLE
Integrate with AnyList

### ISSUE THREAD

**Issue by DavidLozzi** [chrisparnin/pm#3]
Can you provide integration with AnyList, a great iOS list taking service... Also, how about iCloud, and link with my default reminders?

Thanks,
David

**Comment by chrisparnin** [comment]
@DavidLozzi 

Both sound like great ideas, but I don't know if either are feasible at the moment.  I did not see any mention of a public API for connecting with AnyList.  I did just send an email to the developers to see if they did have any plans for an API.  For iCloud, it does not look like they have opened up the service to non iOS devices or web apps:

http://stackoverflow.com/questions/7773920/iphone-and-webapp-sync-through-icloud

**Comment by chrisparnin** [comment]
Otherwise, there might be some unofficial ways to access iCloud:

https://github.com/mindcollapse/iCloud-API
